name: Juice Shop DAST Scan

on:
  workflow_dispatch: # manuel çalıştırmak için
  push:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start Juice Shop Docker Container
      run: |
        docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
        sleep 20  # Juice Shop'un tamamen ayağa kalkması için bekle

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        fail_action: false
        cmd_options: '-config api.disablekey=true'

    - name: Stop Juice Shop Container
      if: always()
      run: |
        docker stop juice-shop
        docker rm juice-shop
