name: DAST Scan on example.com

on:
  workflow_dispatch: # Manuel çalıştırmak için
  push:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://example.com'
        fail_action: false
        cmd_options: '-config api.disablekey=true'
