name: Docker Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t yas1ny1lmaz/juice-shop .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag yas1ny1lmaz/juice-shop yas1ny1lmaz/juice-shop:latest
          docker push yas1ny1lmaz/juice-shop:latest
