name: Docker Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t yas1ny1lmaz/juice-shop .
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to GHCR
        run: |
          docker tag yas1ny1lmaz/juice-shop ghcr.io/yas1ny1lmaz/juice-shop:latest
          docker push ghcr.io/yas1ny1lmaz/juice-shop:latest
