name: GitLeaks Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Her gün gece yarısı çalıştır

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Tüm commit geçmişini al

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v3
        with:
          sarif-report: gitleaks-report.sarif
          config-path: .github/gitleaks.toml # İsteğe bağlı özel config

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-report.sarif
